18-rails-validations/config/routes.rb
Rails.application.routes.draw do
  resources :cohorts
  resources :students, except: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

18-rails-validations/app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students
  # goal: validate the name
  # has actually be there
  validates :name, presence: true
  # not a number
  # min and max length
  validates :name, length: { in: 2..20 }
  # not duplicated
  validates :name, uniqueness: true
end

18-rails-validations/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort
end

18-rails-validations/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

18-rails-validations/app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def new
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)

    if @cohort.save
      redirect_to cohort_path(@cohort.id)
    else
      render :new
    end
  end

  def edit
    @cohort = Cohort.find(params[:id])
    # implicit rendering
  end

  def update
    @cohort = Cohort.find(params[:id])

    if @cohort.update(cohort_params)
      redirect_to "/cohorts/#{@cohort.id}"
    else
      render :edit
    end
  end

  def delete
    Cohort.destroy(params[:id])
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name)
  end
end

18-rails-validations/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
    @cohorts = Cohort.all
    render :new
  end

  def create
    @student = Student.new(name: params[:name],
                           cohort_id: params[:cohort_id])
    if @student.save
      redirect_to student_path(@student)
    else
      @message = "Your student couldn't be saved."
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
    @cohorts = Cohort.all
    render :edit
  end

  def update
    @student = Student.find(params[:id])
    byebug
    @student.update(student_params)
    redirect_to student_path(@student)
  end

  def index
    @students = Student.all
    # render :index
  end

  def show
    @student = Student.find(params[:id])
    render :show
  end

  def student_params
    params.permit(:name, :cohort_id)
  end

end

18-rails-validations/app/helpers/cohorts_helper.rb
module CohortsHelper
end

18-rails-validations/app/helpers/students_helper.rb
module StudentsHelper
end

18-rails-validations/app/views/cohorts/edit.html.erb
<%= @cohort.name %>
<form action="/cohorts/<%= @cohort.id %>" method="post">
  <input name="_method" type="hidden" value="patch" />
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    <input type="text" name="cohort[name]" value="<%= @cohort.name %>">
  </label>

  <input type="submit">
</form>


<% @cohort.errors.each do |field, message| %>
  <span style="color: red">
    <%= field %>: <%= message %>
  <span>
<% end %>

18-rails-validations/app/views/cohorts/index.html.erb
<h1>Cohorts</h1>
<nav>
  <ul>
    <li>
      <a href="/cohorts/new">Create new cohort</a>
    </li>
  </ul>
</nav>
<ul>
  <% @cohorts.each do |cohort| %>
    <li>
      <a href="/cohorts/<%= cohort.id %>"><%= cohort.name %></a>
    </li>
  <% end %>
</ul>

18-rails-validations/app/views/cohorts/new.html.erb
<form action="/cohorts" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    <input type="text" name="cohort[name]" value="<%= @cohort.name %>">
  </label>

  <input type="submit">
</form>


<% @cohort.errors.each do |field, message| %>
  <span style="color: red">
    <%= field %>: <%= message %>
  <span>
<% end %>

18-rails-validations/app/views/cohorts/show.html.erb
<h1><%= @cohort.name %></h1>

<h3>Enrolled Students</h3>
<ul>
  <% @cohort.students.each do |student| %>
    <li><%= student.name %></li>
  <% end %>
</ul>

<a href="/cohorts/<%= @cohort.id %>/edit">Edit</a>

18-rails-validations/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFormsRest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

18-rails-validations/app/views/students/edit.html.erb
<h1>Edit student:</h1>

<%= form_tag(student_path(@student), method: "PUT") do %>
  <%= label_tag(:name, "Student Name: ") %>
  <%= text_field_tag(:name, @student.name) %>
  <br />
  <%= label_tag(:cohort_id, "Cohort: ") %>
  <select name="cohort_id">
    <% @cohorts.each do |cohort| %>
      <option value="<%= cohort.id %>">
        <%= cohort.name %>
      </option>
    <% end %>
  </select>
  <br />
  <%= submit_tag("Save") %>
<% end %>

18-rails-validations/app/views/students/index.html.erb
<h1>List of Students</h1>

<ul>
  <% @students.each do |student| %>
    <li><%= link_to(student.name, student_path(student.id)) %></li>
  <% end %>
</ul>

18-rails-validations/app/views/students/new.html.erb
<h1>Add a new student:</h1>

<% if @message %>
  <p><%= @message %></p>
<% end %>

<%= form_tag(students_path) do %>
  <%= label_tag(:name, "Student Name: ") %>
  <%= text_field_tag(:name, @student.name) %>
  <br />
  <%= label_tag(:cohort_id, "Cohort: ") %>
  <select name="cohort_id">
    <% @cohorts.each do |cohort| %>
      <option value="<%= cohort.id %>">
        <%= cohort.name %>
      </option>
    <% end %>
  </select>
  <br />
  <%= submit_tag("Save") %>
<% end %>

18-rails-validations/app/views/students/show.html.erb
<h2>Name: <%= @student.name %></h2>
<h2>Cohort:
  <%= link_to(@student.cohort.name, cohort_path(@student.cohort)) %>
</h2>

<%= link_to("Edit this student", edit_student_path(@student)) %>