20-rails-auth/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :posts
  resources :users, only: [:new, :create]

  get '/login', to: 'login#new'
  post '/login', to: 'login#create'
  delete '/logout', to: 'login#destroy'
end

20-rails-auth/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_tags
  has_many :tags, through: :post_tags

  validates :title, presence: true, length: { minimum: 5 }
  validates :content, presence: true, length: { minimum: 60 }

  def tag_names
    self.tags.map(&:name).join(", ")
  end

  def tag_names=(new_tags)
    self.tags = new_tags.split(", ").map { |name| Tag.find_or_create_by(name: name) }
  end
end

20-rails-auth/app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

20-rails-auth/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags

  validates :name, presence: true,
            length: { minimum: 4 },
            uniqueness: { case_sensitive: false }
end

20-rails-auth/app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  validates :name, presence: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
end

20-rails-auth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end

  def authorize!
    unless current_user
      flash[:notice] = "You need to be logged in to do that."
      redirect_to :root
    end
  end
end

20-rails-auth/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      redirect_to :root
    else
      flash[:notice] = "Not a valid login. Bye."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

20-rails-auth/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:new, :create, :index]
  before_action :authorize!, except: [:show, :index]

  def new
    @users = User.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def index
    # byebug
    @posts = Post.all
  end

  def show
  end

  def edit
    @users = User.all
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    if @post.user_id == current_user.id
      @post.destroy
    else
      flash[:notice] = "You can only mess with your own stuff."
    end
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :tag_names, :content, :published_at)
  end
end

20-rails-auth/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :root
    else
#      byebug
      flash[:error] = "We couldn't save your user."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password)
  end

end

20-rails-auth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blerg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if current_user %>
        <%= link_to("Logout", logout_path, method: :delete) %>
      <% else %>
        <%= link_to("Login", login_path) %> |
        <%= link_to("Signup", new_user_path) %>
      <% end %>
    </nav>

    <% if flash[:error] %>
      <p style="color: red">
        <%= flash[:error] %>
      </p>
    <% elsif flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>

    <% if current_user %>
      <p>Hello, <%= current_user.name %>!!!</p>
    <% end %>

    <%= yield %>
  </body>
</html>

20-rails-auth/app/views/login/new.html.erb
<h1>Login</h1>

<%= form_tag(action: "create") do %>
  <%= label_tag("Username") %>
  <%= text_field_tag("username") %>

  <%= label_tag("Password") %>
  <%= password_field_tag("password") %>

  <%= submit_tag("Login") %>
<% end %>

20-rails-auth/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <%= f.collection_select(:user_id, @users, :id, :username) %>
    <%= f.text_field :title %>
    <%= f.text_field :tag_names %>
    <%= f.date_select :published_at %>
    <%= f.text_area :content%>
    <%= f.submit %>
<% end %>

20-rails-auth/app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form" %>

<%= link_to("Back to post", post_path(@post)) %>

20-rails-auth/app/views/posts/index.html.erb
<h1>Blog Posts...</h1>

<ul>
    <% @posts.each do |post| %>
        <li><%= link_to(post.title, post_path(post)) %></li>
    <% end %>
</ul>

<%= link_to("Add post", new_post_path) %>

<br/>

<%= link_to("Sign up", new_user_path) %>

20-rails-auth/app/views/posts/new.html.erb
<h1>Add a new post</h1>

<%= render "form" %>

<%= link_to("Back to index", posts_path) %>

20-rails-auth/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h3>Written: <%= time_ago_in_words(@post.published_at) %> ago by <%= @post.user.username %></h3>
<h3>Tags: <%= @post.tag_names %></h3>

<p>
    <%= @post.content %>
</p>

<%= link_to("Edit post", edit_post_path(@post)) %>
<%= link_to("Delete post", post_path(@post), method: :delete) %>

<%= link_to("Back to index", posts_path) %>

20-rails-auth/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= f.label(:name, "Name") %>
  <%= f.text_field :name %>
  <%= f.label(:username, "Username") %>
  <%= f.text_field :username %>
  <%= f.label(:password, "Password") %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>